[package]
name = "senseki-app"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { workspace = true, features = ["serde"] }
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.3", features = ["csr"] }
serde.workspace = true
serde_json.workspace = true
