//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub session_date: Date,
    #[sea_orm(column_type = "Text", nullable)]
    pub notes: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub title: Option<String>,
    pub start_gsp: Option<i32>,
    pub end_gsp: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::gsp_records::Entity")]
    GspRecords,
    #[sea_orm(has_many = "super::matches::Entity")]
    Matches,
}

impl Related<super::gsp_records::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GspRecords.def()
    }
}

impl Related<super::matches::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Matches.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
